= stown documentation
Ralph Seichter
:doctype: article
:revdate: {docdate}
:revnumber: 0.10.7
:version-label!:
:copyright: © 2025 Ralph Seichter
:encoding: UTF-8
:hyphens: en
:lang: en
// :keywords: TODO, foo, bar
:media: screen
:pagenums!:
:pdf-version: 1.7
:sectanchors:
:sectnums:
:subject: Official documentation for the "stown" symlink manager
:xrefstyle: short

== About

Stow file system objects by managing symlinks. "stown" was inspired by
https://www.gnu.org/software/stow/[GNU Stow], which I found very useful but too
unwieldly for my personal use. GNU Stow relies on a number of Perl modules and
can be a hassle to install on minimalistic systems. In contrast, stown only
requires Python 3.9 or newer, without additional modules.

If you are looking for a lightweight tool instead of a full-fledged symlink
farm manager, stown might be for you.

Copyright © 2025 Ralph Seichter. Licensed under <<_license,GPLv3+>>. Source
code is https://github.com/rseichter/stown[available here]. Documentation is
provided in https://www.seichter.de/stown/[HTML] and
https://www.seichter.de/stown/stown.pdf[PDF] format.

== Installing

To install the https://pypi.org/project/stown/[PyPI package], you can use
this shell command:

```bash
pip install stown
```

== Usage

*Always create backups before using stown!*

The following example simulates linking the contents of a dotfile repository to
a user's home directory. The `--dry-run` flag causes the necessary steps to be
printed only; no changes will be made.

```bash
stown --dry-run $HOME /path/to/dotfiles
```

=== Command line options

----
$ stown --help

include::usage.txt[]
----

=== Environment

The environment variable `STOWN_LOGLEVEL` can be used like the `--loglevel`
option. Pick one of the predefined Python logging levels CRITICAL, ERROR,
WARNING, INFO or DEBUG.

== Strategy

With default settings, stown will abort operations to protect existing target
file objects (symlinks, files and directories). This can however lead to
half-finished jobs, so using `--dry-run` prior to any live operation is
recommended. You can use the `--force` flag to permit overwriting existing file
objects, but this is inherently risky. Remember to create backups beforehand,
because here be monsters!

Sources are processed in the order specified by the user. In case of name
collisions, later changes may not override earlier ones unless `--force`
is specified.

If directory `mike` originally contains the following:

----
include::before.txt[]
----

This is the resulting content after `stow --force zulu alpha bravo`:

----
include::after.txt[]
----

Symlinks are created using relative paths with stown's default settings. Using
the `--absolute` flag changes the path type. Links with relative paths can make
changing the directory structure easier in certain circumstances. Renaming the
parent folder `mike` to `alice` would not break the relative links shown above.

Unless disabled via the `--no-dot` option, the prefix `dot-` in source names is
converted to a leading dot character in symlinks, as shown with
`zulu/.editorconfig` pointing to `bravo/dot-editorconfig`. This makes handling
dotfiles easier, disabling their respective special effects and lifting their
"hidden" status.

== Support

For questions regarding stown and its use, please see the
https://github.com/rseichter/stown/discussions[discussions] section. If you are
experiencing technical problems, you can
https://github.com/rseichter/stown/issues[file an issue] instead.

== License

Copyright {copyright}

This file is part of "stown".

stown is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

stown is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
stown. If not, see <https://www.gnu.org/licenses/>.
