= stown symlink manager
Ralph Seichter <stown@seichter.de>
:doctype: article
:revdate: {docdate}
:revnumber: 1.2.1.dev2
:version-label!:
:copyright: © 2025,2026 Ralph Seichter
:encoding: UTF-8
:hyphens: en
:lang: en
:keywords: symlink, lightweight, dotfiles
:media: screen
:pagenums!:
:pdf-version: 1.7
:reproducible:
:sectanchors:
:sectnums:
:subject: Documentation for the "stown" symlink manager
:xrefstyle: short

[#about]
== About

"stown" manages file system object mapping via symlinks. It was inspired by GNU
Stow, which I found very useful but too unwieldly for my personal use. GNU Stow
relies on a number of Perl modules and can be a hassle to install on
minimalistic systems. In contrast, stown requires only Python 3.9 or newer,
without any additional dependencies.

If you are looking for a lightweight tool instead of a full-fledged symlink
farm manager, stown might be for you.

Documentation is provided in https://www.seichter.de/stown/[HTML] and
https://www.seichter.de/stown/stown.pdf[PDF] format. Source code is hosted
https://github.com/rseichter/stown[here].

[#install]
== Installing

=== Requirements

stown requires Python version 3.9 or newer. That's all.

=== All platforms

The first option is to install the https://pypi.org/project/stown/[PyPI
package] using Python's pip utility, available for all platforms.

[source,bash]
----
pip install stown
----

Depending on your OS, https://pip.pypa.io/en/stable/[pip] may need to be
installed first, but it is often available by default. On Debian family
systems, the matching package is typically called `python3-pip`. If your
environment is bare-bones and lacks a package manager, there is also Python's
built-in
https://docs.python.org/3/library/ensurepip.html#module-ensurepip[ensurepip]
module you can use.

=== Arch Linux

Arch users can install the https://aur.archlinux.org/packages/stown[AUR
package] as a convenient alternative to the PyPI package.

=== NixOS and macOS

The https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/st/stown/package.nix[stown]
package is suitable for all platforms supported by a Nix package manager
implementation, e.g. NixOS and macOS.

[#cli]
== Command line options
[%unbreakable]
----
include::usage.txt[]
----

[#example]
== Usage example

The following example simulates linking the contents of a dotfile repository to
a user's home directory. The `--dry-run` flag causes the necessary steps to be
printed only; no changes will be made.

[source,bash]
----
stown --dry-run $HOME /path/to/dotfiles
----

[#strategy]
== Strategy

Terminology: In stown parlance, _source_ means any existing file object
(regular file, directory or symlink). _Targets_ are paths in the file system
where stown is meant to create symlinks pointing to sources.

[#overview]
=== Overview

When used with default options, stown will routinely abort operations in an
attempt to protect existing targets. This can however lead to half-finished
jobs. Using `--dry-run` prior to any live operation is recommended to lower
that risk. Note that stown limits its recursive approach to managing links to a
maximum depth of 10, which is typically sufficient. The `--depth` option can be
used to change the limit.

WARNING: Always create backups before using stown, because here be monsters!

Using the `--force` flag gives stown explicit permission to overwrite existing
file objects. Sources are processed in the order specified by the user. Already
existing targets may not be overwritten, unless permission is granted via
either the `--force` or `--override` options. Override, a feature introduced in
stown 1.1.0, matches target names against a user-defined
https://docs.python.org/3/library/re.html#regular-expression-syntax[regular
expression] (RE).

[source,bash]
----
# Use quotes to protect RE from shell interpolation
stown --override '\.(json|toml)$' sometarget somesource
----

RE are powerful, but they can also lead to surprises for those unfamiliar with
their use: For instance, the regular expression `.c` matches "foo.c" but also
".conf", "sketch" and countless other strings.

[#scenario]
=== Example scenario

As a more in-depth example, let us imagine a directory `mike` originally
containg the following:

[%unbreakable]
----
include::before.txt[]
----

This is the content after `stow --force --ignore '\.txt$' zulu alpha bravo`:

[%unbreakable]
----
include::after.txt[]
----

Symlinks are created using relative paths with stown's default settings. Using
the `--absolute` flag changes the path type. Links with relative paths can make
changing the directory structure easier. For example, renaming the parent
folder `mike` to `november` would not break the relative links shown above.

Unless disabled via the `--no-dot` option, the prefix `dot-` in source names is
converted to a leading dot character in symlinks, as shown with
`zulu/.editorconfig` pointing to `bravo/dot-editorconfig`. This makes handling
dotfiles easier, disabling their respective special effects and lifting their
"hidden" status.

Like the `--override` option, `--ignore` takes a regular expression argument.
However, while override matches targets, the ignore option matches sources.
stown uses a small but reasonable default ignore pattern. If the outcome of a
run is not what you expected, try the INFO loglevel to see if certain sources
are being ignored, possibly requiring you to specify a custom ignore argument.
An empty string RE pattern turns the ignore feature off.

[#env]
== Environment variables

* `STOWN_LOGLEVEL` can be used like the `--loglevel` option. Supported values
  are the Python's predefined  logging levels CRITICAL, ERROR, WARNING (the
  default), INFO or DEBUG. Values are case insensitive. CRITICAL will
  effectively silence stown.

* `STOWN_LOGPATH` corresponds to the `--logpath` option. As per convention, a
  standalone dash `-` is interpreted as an alias for the standard output
  stream, which is also the default.

[#support]
== Support

For questions regarding stown and its use, please use the
https://github.com/rseichter/stown/discussions[discussions] section. If you are
experiencing technical problems, you can
https://github.com/rseichter/stown/issues[file an issue] instead. Both methods
allow other users to participate. If privacy is a concern, you can use
mailto:{email}[email] to contact me.

Note that my support offer is strictly voluntary.


[#legal]
== License

Copyright {copyright}

This file is part of "stown".

stown is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

stown is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
stown. If not, see <https://www.gnu.org/licenses/>.
