# vim: et ts=2 sw=2
---
name: Build on push (GitHub)

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.repository != '' }}
    environment:
      name: dev
    env:
      PYTHONPATH: '.:src'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Stamp with commit SHA
        run: |
          rev=$(git rev-parse --short $GITHUB_SHA)
          echo $rev
          sed -E -i "s/^(COMMIT_SHA =).+/\1 \"$rev\"/" src/stown/*.py

      - name: Lint with flake8
        run: |
          flake8 . --config=.flake8 --select=E9,F63,F7,F82
          flake8 . --config=.flake8 --exit-zero

      - name: Run unit tests with coverage analysis
        run: |
          coverage run -m unittest discover -s tests -v
          coverage report -m

      - name: Build
        run: python -m build
